name: causal_uganda
channels:
  - krinsman
dependencies:
# For setting up and running Jupyter notebooks
  - jupyter=1.0.0
  - r-irkernel=0.8.11
# For installing RStudio in the virtual environment
  - rstudio=1.1.423
# Available in the krinsman channel but not the default
  - r-tmle=1.3.0_1
  - r-superlearner=2.0_23
  - r-ck37r=1.0.0
  - r-sl3=1.0.0
  - r-screening=0.0.0.9000
  - r-arm=1.10_1
# Available in the default Anaconda channel
  - r-ggplot2=2.2.1
  - r-dplyr=0.7.4
  - r-magrittr=1.5
  - r-foreign=0.8_69
  - r-caret=6.0_78
  - r-data.table=1.10.4_3
  - r-xgboost=0.7
  - r-foreach=1.4.4
  - r-glmnet=2.0_13
  # For the code in Uganda_DAG.R
  - r-diagrammer=0.9.2