name: causal_uganda
channels:
  - krinsman
dependencies:
  - jupyter=1.0.0
  - r-irkernel=0.8.11
  - r-tmle=1.3.0_1
  - r-superlearner=2.0_23
  - r-ck37r=1.0.0
  - r-sl3=1.0.0
  - r-screening=0.0.0.9000
  - r-arm=1.10_1
  - r-ggplot2=2.2.1
  - r-dplyr=0.7.4
  - r-magrittr=1.5
  - r-foreign
  - r-caret
  - r-data.table
  - r-xgboost
  - r-foreach
  - r-glmnet